/*
TraceTest

OpenAPI definition for TraceTest endpoint and resources

API version: 0.2.1
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
)

// checks if the TestSuiteResourceList type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &TestSuiteResourceList{}

// TestSuiteResourceList struct for TestSuiteResourceList
type TestSuiteResourceList struct {
	Count *int32              `json:"count,omitempty"`
	Items []TestSuiteResource `json:"items,omitempty"`
}

// NewTestSuiteResourceList instantiates a new TestSuiteResourceList object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewTestSuiteResourceList() *TestSuiteResourceList {
	this := TestSuiteResourceList{}
	return &this
}

// NewTestSuiteResourceListWithDefaults instantiates a new TestSuiteResourceList object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewTestSuiteResourceListWithDefaults() *TestSuiteResourceList {
	this := TestSuiteResourceList{}
	return &this
}

// GetCount returns the Count field value if set, zero value otherwise.
func (o *TestSuiteResourceList) GetCount() int32 {
	if o == nil || isNil(o.Count) {
		var ret int32
		return ret
	}
	return *o.Count
}

// GetCountOk returns a tuple with the Count field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *TestSuiteResourceList) GetCountOk() (*int32, bool) {
	if o == nil || isNil(o.Count) {
		return nil, false
	}
	return o.Count, true
}

// HasCount returns a boolean if a field has been set.
func (o *TestSuiteResourceList) HasCount() bool {
	if o != nil && !isNil(o.Count) {
		return true
	}

	return false
}

// SetCount gets a reference to the given int32 and assigns it to the Count field.
func (o *TestSuiteResourceList) SetCount(v int32) {
	o.Count = &v
}

// GetItems returns the Items field value if set, zero value otherwise.
func (o *TestSuiteResourceList) GetItems() []TestSuiteResource {
	if o == nil || isNil(o.Items) {
		var ret []TestSuiteResource
		return ret
	}
	return o.Items
}

// GetItemsOk returns a tuple with the Items field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *TestSuiteResourceList) GetItemsOk() ([]TestSuiteResource, bool) {
	if o == nil || isNil(o.Items) {
		return nil, false
	}
	return o.Items, true
}

// HasItems returns a boolean if a field has been set.
func (o *TestSuiteResourceList) HasItems() bool {
	if o != nil && !isNil(o.Items) {
		return true
	}

	return false
}

// SetItems gets a reference to the given []TestSuiteResource and assigns it to the Items field.
func (o *TestSuiteResourceList) SetItems(v []TestSuiteResource) {
	o.Items = v
}

func (o TestSuiteResourceList) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o TestSuiteResourceList) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !isNil(o.Count) {
		toSerialize["count"] = o.Count
	}
	if !isNil(o.Items) {
		toSerialize["items"] = o.Items
	}
	return toSerialize, nil
}

type NullableTestSuiteResourceList struct {
	value *TestSuiteResourceList
	isSet bool
}

func (v NullableTestSuiteResourceList) Get() *TestSuiteResourceList {
	return v.value
}

func (v *NullableTestSuiteResourceList) Set(val *TestSuiteResourceList) {
	v.value = val
	v.isSet = true
}

func (v NullableTestSuiteResourceList) IsSet() bool {
	return v.isSet
}

func (v *NullableTestSuiteResourceList) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableTestSuiteResourceList(val *TestSuiteResourceList) *NullableTestSuiteResourceList {
	return &NullableTestSuiteResourceList{value: val, isSet: true}
}

func (v NullableTestSuiteResourceList) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableTestSuiteResourceList) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
