FROM alpine

ENV PATH="$PATH:/app"
ENV TRACETEST_API_KEY ""

WORKDIR /app

# Setup Tracetest CLI
COPY ./tracetest /app/tracetest
COPY ./agent/entrypoint.sh /app/entrypoint.sh
RUN chmod +x /app/entrypoint.sh

USER root
RUN echo "https://dl-cdn.alpinelinux.org/alpine/edge/main" > /etc/apk/repositories \
  && echo "https://dl-cdn.alpinelinux.org/alpine/edge/community" >> /etc/apk/repositories \
  && echo "https://dl-cdn.alpinelinux.org/alpine/edge/testing" >> /etc/apk/repositories \
  && echo "https://dl-cdn.alpinelinux.org/alpine/v3.16/main" >> /etc/apk/repositories \
  && echo "https://dl-cdn.alpinelinux.org/alpine/v3.16/community" \
  && apk upgrade -U -a \
  && apk add \
  libstdc++ \
  chromium \
  harfbuzz \
  nss \
  freetype \
  ttf-freefont \
  font-noto-emoji \
  wqy-zenhei \
  && rm -rf /var/cache/* \
  && mkdir /var/cache/apk

# Playwright
ENV PLAYWRIGHT_CHROMIUM_EXECUTABLE_PATH=/usr/lib/chromium/chromium \
  PLAYWRIGHT_SKIP_BROWSER_DOWNLOAD=1

# Setup additional runtimes used by triggers
RUN apk add nodejs npm

ENTRYPOINT ["/app/entrypoint.sh"]

