/*
 * Project X
 *
 * OpenAPI definition for project X endpoint and resources
 *
 * API version: 0.0.1
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi

type Assertion struct {

	// ID
	Id string `json:"id,omitempty"`

	// Defines the scope where the sought property/ies is located
	Selector string `json:"selector,omitempty"`

	// Defines the expected value of the property/ies
	Comparable string `json:"comparable,omitempty"`

	// Defines how the value of sought property/ies should be compared For example lt (less then), gt (greater then), eq (equals), in (contains)
	Operator string `json:"operator,omitempty"`

	Successful bool `json:"successful,omitempty"`
}

// AssertAssertionRequired checks if the required fields are not zero-ed
func AssertAssertionRequired(obj Assertion) error {
	return nil
}

// AssertRecurseAssertionRequired recursively checks if required fields are not zero-ed in a nested slice.
// Accepts only nested slice of Assertion (e.g. [][]Assertion), otherwise ErrTypeAssertionError is thrown.
func AssertRecurseAssertionRequired(objSlice interface{}) error {
	return AssertRecurseInterfaceRequired(objSlice, func(obj interface{}) error {
		aAssertion, ok := obj.(Assertion)
		if !ok {
			return ErrTypeAssertionError
		}
		return AssertAssertionRequired(aAssertion)
	})
}
