/*
 * TraceTest
 *
 * OpenAPI definition for TraceTest endpoint and resources
 *
 * API version: 0.0.1
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi

type TestServiceUnderTest struct {

	// ID
	Id string `json:"id,omitempty"`

	Request HttpRequest `json:"request,omitempty"`
}

// AssertTestServiceUnderTestRequired checks if the required fields are not zero-ed
func AssertTestServiceUnderTestRequired(obj TestServiceUnderTest) error {
	if err := AssertHttpRequestRequired(obj.Request); err != nil {
		return err
	}
	return nil
}

// AssertRecurseTestServiceUnderTestRequired recursively checks if required fields are not zero-ed in a nested slice.
// Accepts only nested slice of TestServiceUnderTest (e.g. [][]TestServiceUnderTest), otherwise ErrTypeAssertionError is thrown.
func AssertRecurseTestServiceUnderTestRequired(objSlice interface{}) error {
	return AssertRecurseInterfaceRequired(objSlice, func(obj interface{}) error {
		aTestServiceUnderTest, ok := obj.(TestServiceUnderTest)
		if !ok {
			return ErrTypeAssertionError
		}
		return AssertTestServiceUnderTestRequired(aTestServiceUnderTest)
	})
}
