/*
 * TraceTest
 *
 * OpenAPI definition for TraceTest endpoint and resources
 *
 * API version: 0.0.1
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi

type HttpResponseHeaders struct {
	Key string `json:"key,omitempty"`

	Value string `json:"value,omitempty"`
}

// AssertHttpResponseHeadersRequired checks if the required fields are not zero-ed
func AssertHttpResponseHeadersRequired(obj HttpResponseHeaders) error {
	return nil
}

// AssertRecurseHttpResponseHeadersRequired recursively checks if required fields are not zero-ed in a nested slice.
// Accepts only nested slice of HttpResponseHeaders (e.g. [][]HttpResponseHeaders), otherwise ErrTypeAssertionError is thrown.
func AssertRecurseHttpResponseHeadersRequired(objSlice interface{}) error {
	return AssertRecurseInterfaceRequired(objSlice, func(obj interface{}) error {
		aHttpResponseHeaders, ok := obj.(HttpResponseHeaders)
		if !ok {
			return ErrTypeAssertionError
		}
		return AssertHttpResponseHeadersRequired(aHttpResponseHeaders)
	})
}
