/*
 * TraceTest
 *
 * OpenAPI definition for TraceTest endpoint and resources
 *
 * API version: 0.2.1
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi

type GetTransactions200Response struct {
	Count int32 `json:"count,omitempty"`

	Items []TransactionResource `json:"items,omitempty"`
}

// AssertGetTransactions200ResponseRequired checks if the required fields are not zero-ed
func AssertGetTransactions200ResponseRequired(obj GetTransactions200Response) error {
	for _, el := range obj.Items {
		if err := AssertTransactionResourceRequired(el); err != nil {
			return err
		}
	}
	return nil
}

// AssertRecurseGetTransactions200ResponseRequired recursively checks if required fields are not zero-ed in a nested slice.
// Accepts only nested slice of GetTransactions200Response (e.g. [][]GetTransactions200Response), otherwise ErrTypeAssertionError is thrown.
func AssertRecurseGetTransactions200ResponseRequired(objSlice interface{}) error {
	return AssertRecurseInterfaceRequired(objSlice, func(obj interface{}) error {
		aGetTransactions200Response, ok := obj.(GetTransactions200Response)
		if !ok {
			return ErrTypeAssertionError
		}
		return AssertGetTransactions200ResponseRequired(aGetTransactions200Response)
	})
}
