/*
 * TraceTest
 *
 * OpenAPI definition for TraceTest endpoint and resources
 *
 * API version: 0.2.1
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi

type PollingInfoPeriodic struct {
	NumberSpans int32 `json:"numberSpans,omitempty"`

	NumberIterations int32 `json:"numberIterations,omitempty"`
}

// AssertPollingInfoPeriodicRequired checks if the required fields are not zero-ed
func AssertPollingInfoPeriodicRequired(obj PollingInfoPeriodic) error {
	return nil
}

// AssertRecursePollingInfoPeriodicRequired recursively checks if required fields are not zero-ed in a nested slice.
// Accepts only nested slice of PollingInfoPeriodic (e.g. [][]PollingInfoPeriodic), otherwise ErrTypeAssertionError is thrown.
func AssertRecursePollingInfoPeriodicRequired(objSlice interface{}) error {
	return AssertRecurseInterfaceRequired(objSlice, func(obj interface{}) error {
		aPollingInfoPeriodic, ok := obj.(PollingInfoPeriodic)
		if !ok {
			return ErrTypeAssertionError
		}
		return AssertPollingInfoPeriodicRequired(aPollingInfoPeriodic)
	})
}
