/*
 * TraceTest
 *
 * OpenAPI definition for TraceTest endpoint and resources
 *
 * API version: 0.0.1
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi

// V1InstrumentationLibrary - InstrumentationLibrary is a message representing the instrumentation library information such as the fully qualified name and version.
type V1InstrumentationLibrary struct {

	// An empty instrumentation library name means the name is unknown.
	Name string `json:"name,omitempty"`

	Version string `json:"version,omitempty"`
}

// AssertV1InstrumentationLibraryRequired checks if the required fields are not zero-ed
func AssertV1InstrumentationLibraryRequired(obj V1InstrumentationLibrary) error {
	return nil
}

// AssertRecurseV1InstrumentationLibraryRequired recursively checks if required fields are not zero-ed in a nested slice.
// Accepts only nested slice of V1InstrumentationLibrary (e.g. [][]V1InstrumentationLibrary), otherwise ErrTypeAssertionError is thrown.
func AssertRecurseV1InstrumentationLibraryRequired(objSlice interface{}) error {
	return AssertRecurseInterfaceRequired(objSlice, func(obj interface{}) error {
		aV1InstrumentationLibrary, ok := obj.(V1InstrumentationLibrary)
		if !ok {
			return ErrTypeAssertionError
		}
		return AssertV1InstrumentationLibraryRequired(aV1InstrumentationLibrary)
	})
}
