/*
 * TraceTest
 *
 * OpenAPI definition for TraceTest endpoint and resources
 *
 * API version: 0.2.1
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi

// datastore - Represents a data store structured into the Resources format.
type datastore struct {

	// Represents the type of this resource. It should always be set as 'DataStore'.
	Type string `json:"type,omitempty"`

	Spec DataStore `json:"spec,omitempty"`
}

// AssertDataStoreResourceRequired checks if the required fields are not zero-ed
func AssertDataStoreResourceRequired(obj datastore) error {
	if err := AssertDataStoreRequired(obj.Spec); err != nil {
		return err
	}
	return nil
}

// AssertRecurseDataStoreResourceRequired recursively checks if required fields are not zero-ed in a nested slice.
// Accepts only nested slice of datastore (e.g. [][]datastore), otherwise ErrTypeAssertionError is thrown.
func AssertRecurseDataStoreResourceRequired(objSlice interface{}) error {
	return AssertRecurseInterfaceRequired(objSlice, func(obj interface{}) error {
		aDataStoreResource, ok := obj.(datastore)
		if !ok {
			return ErrTypeAssertionError
		}
		return AssertDataStoreResourceRequired(aDataStoreResource)
	})
}
