/*
 * TraceTest
 *
 * OpenAPI definition for TraceTest endpoint and resources
 *
 * API version: 0.2.1
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi

type ConfigurationResourceList struct {
	Count int32 `json:"count,omitempty"`

	Items []ConfigurationResource `json:"items,omitempty"`
}

// AssertConfigurationResourceListRequired checks if the required fields are not zero-ed
func AssertConfigurationResourceListRequired(obj ConfigurationResourceList) error {
	for _, el := range obj.Items {
		if err := AssertConfigurationResourceRequired(el); err != nil {
			return err
		}
	}
	return nil
}

// AssertRecurseConfigurationResourceListRequired recursively checks if required fields are not zero-ed in a nested slice.
// Accepts only nested slice of ConfigurationResourceList (e.g. [][]ConfigurationResourceList), otherwise ErrTypeAssertionError is thrown.
func AssertRecurseConfigurationResourceListRequired(objSlice interface{}) error {
	return AssertRecurseInterfaceRequired(objSlice, func(obj interface{}) error {
		aConfigurationResourceList, ok := obj.(ConfigurationResourceList)
		if !ok {
			return ErrTypeAssertionError
		}
		return AssertConfigurationResourceListRequired(aConfigurationResourceList)
	})
}
