/*
 * TraceTest
 *
 * OpenAPI definition for TraceTest endpoint and resources
 *
 * API version: 0.2.1
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi

type TestSpec struct {
	Name *string `json:"name,omitempty"`

	Selector string `json:"selector,omitempty"`

	SelectorParsed Selector `json:"selectorParsed,omitempty"`

	Assertions []string `json:"assertions,omitempty"`
}

// AssertTestSpecRequired checks if the required fields are not zero-ed
func AssertTestSpecRequired(obj TestSpec) error {
	if err := AssertSelectorRequired(obj.SelectorParsed); err != nil {
		return err
	}
	return nil
}

// AssertRecurseTestSpecRequired recursively checks if required fields are not zero-ed in a nested slice.
// Accepts only nested slice of TestSpec (e.g. [][]TestSpec), otherwise ErrTypeAssertionError is thrown.
func AssertRecurseTestSpecRequired(objSlice interface{}) error {
	return AssertRecurseInterfaceRequired(objSlice, func(obj interface{}) error {
		aTestSpec, ok := obj.(TestSpec)
		if !ok {
			return ErrTypeAssertionError
		}
		return AssertTestSpecRequired(aTestSpec)
	})
}
