/*
 * TraceTest
 *
 * OpenAPI definition for TraceTest endpoint and resources
 *
 * API version: 0.2.1
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi

type TestTrigger struct {
	Type string `json:"type,omitempty"`

	HttpRequest HttpRequest `json:"httpRequest,omitempty"`
}

// AssertTestTriggerRequired checks if the required fields are not zero-ed
func AssertTestTriggerRequired(obj TestTrigger) error {
	if err := AssertHttpRequestRequired(obj.HttpRequest); err != nil {
		return err
	}
	return nil
}

// AssertRecurseTestTriggerRequired recursively checks if required fields are not zero-ed in a nested slice.
// Accepts only nested slice of TestTrigger (e.g. [][]TestTrigger), otherwise ErrTypeAssertionError is thrown.
func AssertRecurseTestTriggerRequired(objSlice interface{}) error {
	return AssertRecurseInterfaceRequired(objSlice, func(obj interface{}) error {
		aTestTrigger, ok := obj.(TestTrigger)
		if !ok {
			return ErrTypeAssertionError
		}
		return AssertTestTriggerRequired(aTestTrigger)
	})
}
