/*
 * TraceTest
 *
 * OpenAPI definition for TraceTest endpoint and resources
 *
 * API version: 0.2.1
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi

// MonitorResource - Represents a Monitor structured into the Resources format.
type MonitorResource struct {

	// Represents the type of this resource. It should always be set as 'Monitor'.
	Type string `json:"type,omitempty"`

	Spec Monitor `json:"spec,omitempty"`
}

// AssertMonitorResourceRequired checks if the required fields are not zero-ed
func AssertMonitorResourceRequired(obj MonitorResource) error {
	if err := AssertMonitorRequired(obj.Spec); err != nil {
		return err
	}
	return nil
}

// AssertRecurseMonitorResourceRequired recursively checks if required fields are not zero-ed in a nested slice.
// Accepts only nested slice of MonitorResource (e.g. [][]MonitorResource), otherwise ErrTypeAssertionError is thrown.
func AssertRecurseMonitorResourceRequired(objSlice interface{}) error {
	return AssertRecurseInterfaceRequired(objSlice, func(obj interface{}) error {
		aMonitorResource, ok := obj.(MonitorResource)
		if !ok {
			return ErrTypeAssertionError
		}
		return AssertMonitorResourceRequired(aMonitorResource)
	})
}
