/*
 * TraceTest
 *
 * OpenAPI definition for TraceTest endpoint and resources
 *
 * API version: 0.2.1
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi

import (
	"time"
)

type Summary struct {
	Runs int32 `json:"runs,omitempty"`

	LastState string `json:"lastState,omitempty"`

	LastRunTime time.Time `json:"lastRunTime,omitempty"`
}

// AssertSummaryRequired checks if the required fields are not zero-ed
func AssertSummaryRequired(obj Summary) error {
	return nil
}

// AssertRecurseSummaryRequired recursively checks if required fields are not zero-ed in a nested slice.
// Accepts only nested slice of Summary (e.g. [][]Summary), otherwise ErrTypeAssertionError is thrown.
func AssertRecurseSummaryRequired(objSlice interface{}) error {
	return AssertRecurseInterfaceRequired(objSlice, func(obj interface{}) error {
		aSummary, ok := obj.(Summary)
		if !ok {
			return ErrTypeAssertionError
		}
		return AssertSummaryRequired(aSummary)
	})
}
