/*
 * TraceTest
 *
 * OpenAPI definition for TraceTest endpoint and resources
 *
 * API version: 0.2.1
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi

type OtlpTestConnectionResponse struct {
	SpanCount int32 `json:"spanCount,omitempty"`

	LastSpanTimestamp string `json:"lastSpanTimestamp,omitempty"`
}

// AssertOtlpTestConnectionResponseRequired checks if the required fields are not zero-ed
func AssertOtlpTestConnectionResponseRequired(obj OtlpTestConnectionResponse) error {
	return nil
}

// AssertRecurseOtlpTestConnectionResponseRequired recursively checks if required fields are not zero-ed in a nested slice.
// Accepts only nested slice of OtlpTestConnectionResponse (e.g. [][]OtlpTestConnectionResponse), otherwise ErrTypeAssertionError is thrown.
func AssertRecurseOtlpTestConnectionResponseRequired(objSlice interface{}) error {
	return AssertRecurseInterfaceRequired(objSlice, func(obj interface{}) error {
		aOtlpTestConnectionResponse, ok := obj.(OtlpTestConnectionResponse)
		if !ok {
			return ErrTypeAssertionError
		}
		return AssertOtlpTestConnectionResponseRequired(aOtlpTestConnectionResponse)
	})
}
