/*
 * TraceTest
 *
 * OpenAPI definition for TraceTest endpoint and resources
 *
 * API version: 0.2.1
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi

type TraceidRequest struct {
	Id string `json:"id,omitempty"`
}

// AssertTraceidRequestRequired checks if the required fields are not zero-ed
func AssertTraceidRequestRequired(obj TraceidRequest) error {
	return nil
}

// AssertRecurseTraceidRequestRequired recursively checks if required fields are not zero-ed in a nested slice.
// Accepts only nested slice of TraceidRequest (e.g. [][]TraceidRequest), otherwise ErrTypeAssertionError is thrown.
func AssertRecurseTraceidRequestRequired(objSlice interface{}) error {
	return AssertRecurseInterfaceRequired(objSlice, func(obj interface{}) error {
		aTraceidRequest, ok := obj.(TraceidRequest)
		if !ok {
			return ErrTypeAssertionError
		}
		return AssertTraceidRequestRequired(aTraceidRequest)
	})
}
