// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: tempo-idl/tempo.proto

package tempopb

import (
	context "context"
	fmt "fmt"
	_ "github.com/gogo/protobuf/gogoproto"
	proto "github.com/gogo/protobuf/proto"
	v1 "go.opentelemetry.io/proto/otlp/trace/v1"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion3 // please upgrade the proto package

// Read
type TraceByIDRequest struct {
	TraceID              []byte   `protobuf:"bytes,1,opt,name=traceID,proto3" json:"traceID,omitempty"`
	BlockStart           string   `protobuf:"bytes,2,opt,name=blockStart,proto3" json:"blockStart,omitempty"`
	BlockEnd             string   `protobuf:"bytes,3,opt,name=blockEnd,proto3" json:"blockEnd,omitempty"`
	QueryMode            string   `protobuf:"bytes,5,opt,name=queryMode,proto3" json:"queryMode,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *TraceByIDRequest) Reset()         { *m = TraceByIDRequest{} }
func (m *TraceByIDRequest) String() string { return proto.CompactTextString(m) }
func (*TraceByIDRequest) ProtoMessage()    {}
func (*TraceByIDRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_52a052455dcd7a1f, []int{0}
}
func (m *TraceByIDRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_TraceByIDRequest.Unmarshal(m, b)
}
func (m *TraceByIDRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_TraceByIDRequest.Marshal(b, m, deterministic)
}
func (m *TraceByIDRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_TraceByIDRequest.Merge(m, src)
}
func (m *TraceByIDRequest) XXX_Size() int {
	return xxx_messageInfo_TraceByIDRequest.Size(m)
}
func (m *TraceByIDRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_TraceByIDRequest.DiscardUnknown(m)
}

var xxx_messageInfo_TraceByIDRequest proto.InternalMessageInfo

func (m *TraceByIDRequest) GetTraceID() []byte {
	if m != nil {
		return m.TraceID
	}
	return nil
}

func (m *TraceByIDRequest) GetBlockStart() string {
	if m != nil {
		return m.BlockStart
	}
	return ""
}

func (m *TraceByIDRequest) GetBlockEnd() string {
	if m != nil {
		return m.BlockEnd
	}
	return ""
}

func (m *TraceByIDRequest) GetQueryMode() string {
	if m != nil {
		return m.QueryMode
	}
	return ""
}

type TraceByIDResponse struct {
	Trace                *Trace            `protobuf:"bytes,1,opt,name=trace,proto3" json:"trace,omitempty"`
	Metrics              *TraceByIDMetrics `protobuf:"bytes,2,opt,name=metrics,proto3" json:"metrics,omitempty"`
	XXX_NoUnkeyedLiteral struct{}          `json:"-"`
	XXX_unrecognized     []byte            `json:"-"`
	XXX_sizecache        int32             `json:"-"`
}

func (m *TraceByIDResponse) Reset()         { *m = TraceByIDResponse{} }
func (m *TraceByIDResponse) String() string { return proto.CompactTextString(m) }
func (*TraceByIDResponse) ProtoMessage()    {}
func (*TraceByIDResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_52a052455dcd7a1f, []int{1}
}
func (m *TraceByIDResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_TraceByIDResponse.Unmarshal(m, b)
}
func (m *TraceByIDResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_TraceByIDResponse.Marshal(b, m, deterministic)
}
func (m *TraceByIDResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_TraceByIDResponse.Merge(m, src)
}
func (m *TraceByIDResponse) XXX_Size() int {
	return xxx_messageInfo_TraceByIDResponse.Size(m)
}
func (m *TraceByIDResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_TraceByIDResponse.DiscardUnknown(m)
}

var xxx_messageInfo_TraceByIDResponse proto.InternalMessageInfo

func (m *TraceByIDResponse) GetTrace() *Trace {
	if m != nil {
		return m.Trace
	}
	return nil
}

func (m *TraceByIDResponse) GetMetrics() *TraceByIDMetrics {
	if m != nil {
		return m.Metrics
	}
	return nil
}

type TraceByIDMetrics struct {
	FailedBlocks         uint32   `protobuf:"varint,1,opt,name=failedBlocks,proto3" json:"failedBlocks,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *TraceByIDMetrics) Reset()         { *m = TraceByIDMetrics{} }
func (m *TraceByIDMetrics) String() string { return proto.CompactTextString(m) }
func (*TraceByIDMetrics) ProtoMessage()    {}
func (*TraceByIDMetrics) Descriptor() ([]byte, []int) {
	return fileDescriptor_52a052455dcd7a1f, []int{2}
}
func (m *TraceByIDMetrics) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_TraceByIDMetrics.Unmarshal(m, b)
}
func (m *TraceByIDMetrics) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_TraceByIDMetrics.Marshal(b, m, deterministic)
}
func (m *TraceByIDMetrics) XXX_Merge(src proto.Message) {
	xxx_messageInfo_TraceByIDMetrics.Merge(m, src)
}
func (m *TraceByIDMetrics) XXX_Size() int {
	return xxx_messageInfo_TraceByIDMetrics.Size(m)
}
func (m *TraceByIDMetrics) XXX_DiscardUnknown() {
	xxx_messageInfo_TraceByIDMetrics.DiscardUnknown(m)
}

var xxx_messageInfo_TraceByIDMetrics proto.InternalMessageInfo

func (m *TraceByIDMetrics) GetFailedBlocks() uint32 {
	if m != nil {
		return m.FailedBlocks
	}
	return 0
}

// SearchRequest takes no block parameters and implies a "recent traces" search
type SearchRequest struct {
	// case insensitive partial match
	Tags                 map[string]string `protobuf:"bytes,1,rep,name=Tags,proto3" json:"Tags" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
	MinDurationMs        uint32            `protobuf:"varint,2,opt,name=MinDurationMs,proto3" json:"MinDurationMs,omitempty"`
	MaxDurationMs        uint32            `protobuf:"varint,3,opt,name=MaxDurationMs,proto3" json:"MaxDurationMs,omitempty"`
	Limit                uint32            `protobuf:"varint,4,opt,name=Limit,proto3" json:"Limit,omitempty"`
	Start                uint32            `protobuf:"varint,5,opt,name=start,proto3" json:"start,omitempty"`
	End                  uint32            `protobuf:"varint,6,opt,name=end,proto3" json:"end,omitempty"`
	XXX_NoUnkeyedLiteral struct{}          `json:"-"`
	XXX_unrecognized     []byte            `json:"-"`
	XXX_sizecache        int32             `json:"-"`
}

func (m *SearchRequest) Reset()         { *m = SearchRequest{} }
func (m *SearchRequest) String() string { return proto.CompactTextString(m) }
func (*SearchRequest) ProtoMessage()    {}
func (*SearchRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_52a052455dcd7a1f, []int{3}
}
func (m *SearchRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SearchRequest.Unmarshal(m, b)
}
func (m *SearchRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SearchRequest.Marshal(b, m, deterministic)
}
func (m *SearchRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SearchRequest.Merge(m, src)
}
func (m *SearchRequest) XXX_Size() int {
	return xxx_messageInfo_SearchRequest.Size(m)
}
func (m *SearchRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_SearchRequest.DiscardUnknown(m)
}

var xxx_messageInfo_SearchRequest proto.InternalMessageInfo

func (m *SearchRequest) GetTags() map[string]string {
	if m != nil {
		return m.Tags
	}
	return nil
}

func (m *SearchRequest) GetMinDurationMs() uint32 {
	if m != nil {
		return m.MinDurationMs
	}
	return 0
}

func (m *SearchRequest) GetMaxDurationMs() uint32 {
	if m != nil {
		return m.MaxDurationMs
	}
	return 0
}

func (m *SearchRequest) GetLimit() uint32 {
	if m != nil {
		return m.Limit
	}
	return 0
}

func (m *SearchRequest) GetStart() uint32 {
	if m != nil {
		return m.Start
	}
	return 0
}

func (m *SearchRequest) GetEnd() uint32 {
	if m != nil {
		return m.End
	}
	return 0
}

// SearchBlockRequest takes SearchRequest parameters as well as all information necessary
// to search a block in the backend.
type SearchBlockRequest struct {
	SearchReq            *SearchRequest `protobuf:"bytes,1,opt,name=searchReq,proto3" json:"searchReq,omitempty"`
	BlockID              string         `protobuf:"bytes,2,opt,name=blockID,proto3" json:"blockID,omitempty"`
	StartPage            uint32         `protobuf:"varint,3,opt,name=startPage,proto3" json:"startPage,omitempty"`
	PagesToSearch        uint32         `protobuf:"varint,4,opt,name=pagesToSearch,proto3" json:"pagesToSearch,omitempty"`
	Encoding             string         `protobuf:"bytes,5,opt,name=encoding,proto3" json:"encoding,omitempty"`
	IndexPageSize        uint32         `protobuf:"varint,6,opt,name=indexPageSize,proto3" json:"indexPageSize,omitempty"`
	TotalRecords         uint32         `protobuf:"varint,7,opt,name=totalRecords,proto3" json:"totalRecords,omitempty"`
	DataEncoding         string         `protobuf:"bytes,8,opt,name=dataEncoding,proto3" json:"dataEncoding,omitempty"`
	Version              string         `protobuf:"bytes,9,opt,name=version,proto3" json:"version,omitempty"`
	XXX_NoUnkeyedLiteral struct{}       `json:"-"`
	XXX_unrecognized     []byte         `json:"-"`
	XXX_sizecache        int32          `json:"-"`
}

func (m *SearchBlockRequest) Reset()         { *m = SearchBlockRequest{} }
func (m *SearchBlockRequest) String() string { return proto.CompactTextString(m) }
func (*SearchBlockRequest) ProtoMessage()    {}
func (*SearchBlockRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_52a052455dcd7a1f, []int{4}
}
func (m *SearchBlockRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SearchBlockRequest.Unmarshal(m, b)
}
func (m *SearchBlockRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SearchBlockRequest.Marshal(b, m, deterministic)
}
func (m *SearchBlockRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SearchBlockRequest.Merge(m, src)
}
func (m *SearchBlockRequest) XXX_Size() int {
	return xxx_messageInfo_SearchBlockRequest.Size(m)
}
func (m *SearchBlockRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_SearchBlockRequest.DiscardUnknown(m)
}

var xxx_messageInfo_SearchBlockRequest proto.InternalMessageInfo

func (m *SearchBlockRequest) GetSearchReq() *SearchRequest {
	if m != nil {
		return m.SearchReq
	}
	return nil
}

func (m *SearchBlockRequest) GetBlockID() string {
	if m != nil {
		return m.BlockID
	}
	return ""
}

func (m *SearchBlockRequest) GetStartPage() uint32 {
	if m != nil {
		return m.StartPage
	}
	return 0
}

func (m *SearchBlockRequest) GetPagesToSearch() uint32 {
	if m != nil {
		return m.PagesToSearch
	}
	return 0
}

func (m *SearchBlockRequest) GetEncoding() string {
	if m != nil {
		return m.Encoding
	}
	return ""
}

func (m *SearchBlockRequest) GetIndexPageSize() uint32 {
	if m != nil {
		return m.IndexPageSize
	}
	return 0
}

func (m *SearchBlockRequest) GetTotalRecords() uint32 {
	if m != nil {
		return m.TotalRecords
	}
	return 0
}

func (m *SearchBlockRequest) GetDataEncoding() string {
	if m != nil {
		return m.DataEncoding
	}
	return ""
}

func (m *SearchBlockRequest) GetVersion() string {
	if m != nil {
		return m.Version
	}
	return ""
}

type SearchResponse struct {
	Traces               []*TraceSearchMetadata `protobuf:"bytes,1,rep,name=traces,proto3" json:"traces,omitempty"`
	Metrics              *SearchMetrics         `protobuf:"bytes,2,opt,name=metrics,proto3" json:"metrics,omitempty"`
	XXX_NoUnkeyedLiteral struct{}               `json:"-"`
	XXX_unrecognized     []byte                 `json:"-"`
	XXX_sizecache        int32                  `json:"-"`
}

func (m *SearchResponse) Reset()         { *m = SearchResponse{} }
func (m *SearchResponse) String() string { return proto.CompactTextString(m) }
func (*SearchResponse) ProtoMessage()    {}
func (*SearchResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_52a052455dcd7a1f, []int{5}
}
func (m *SearchResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SearchResponse.Unmarshal(m, b)
}
func (m *SearchResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SearchResponse.Marshal(b, m, deterministic)
}
func (m *SearchResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SearchResponse.Merge(m, src)
}
func (m *SearchResponse) XXX_Size() int {
	return xxx_messageInfo_SearchResponse.Size(m)
}
func (m *SearchResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_SearchResponse.DiscardUnknown(m)
}

var xxx_messageInfo_SearchResponse proto.InternalMessageInfo

func (m *SearchResponse) GetTraces() []*TraceSearchMetadata {
	if m != nil {
		return m.Traces
	}
	return nil
}

func (m *SearchResponse) GetMetrics() *SearchMetrics {
	if m != nil {
		return m.Metrics
	}
	return nil
}

type TraceSearchMetadata struct {
	TraceID              string   `protobuf:"bytes,1,opt,name=traceID,proto3" json:"traceID,omitempty"`
	RootServiceName      string   `protobuf:"bytes,2,opt,name=rootServiceName,proto3" json:"rootServiceName,omitempty"`
	RootTraceName        string   `protobuf:"bytes,3,opt,name=rootTraceName,proto3" json:"rootTraceName,omitempty"`
	StartTimeUnixNano    uint64   `protobuf:"varint,4,opt,name=startTimeUnixNano,proto3" json:"startTimeUnixNano,omitempty"`
	DurationMs           uint32   `protobuf:"varint,5,opt,name=durationMs,proto3" json:"durationMs,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *TraceSearchMetadata) Reset()         { *m = TraceSearchMetadata{} }
func (m *TraceSearchMetadata) String() string { return proto.CompactTextString(m) }
func (*TraceSearchMetadata) ProtoMessage()    {}
func (*TraceSearchMetadata) Descriptor() ([]byte, []int) {
	return fileDescriptor_52a052455dcd7a1f, []int{6}
}
func (m *TraceSearchMetadata) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_TraceSearchMetadata.Unmarshal(m, b)
}
func (m *TraceSearchMetadata) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_TraceSearchMetadata.Marshal(b, m, deterministic)
}
func (m *TraceSearchMetadata) XXX_Merge(src proto.Message) {
	xxx_messageInfo_TraceSearchMetadata.Merge(m, src)
}
func (m *TraceSearchMetadata) XXX_Size() int {
	return xxx_messageInfo_TraceSearchMetadata.Size(m)
}
func (m *TraceSearchMetadata) XXX_DiscardUnknown() {
	xxx_messageInfo_TraceSearchMetadata.DiscardUnknown(m)
}

var xxx_messageInfo_TraceSearchMetadata proto.InternalMessageInfo

func (m *TraceSearchMetadata) GetTraceID() string {
	if m != nil {
		return m.TraceID
	}
	return ""
}

func (m *TraceSearchMetadata) GetRootServiceName() string {
	if m != nil {
		return m.RootServiceName
	}
	return ""
}

func (m *TraceSearchMetadata) GetRootTraceName() string {
	if m != nil {
		return m.RootTraceName
	}
	return ""
}

func (m *TraceSearchMetadata) GetStartTimeUnixNano() uint64 {
	if m != nil {
		return m.StartTimeUnixNano
	}
	return 0
}

func (m *TraceSearchMetadata) GetDurationMs() uint32 {
	if m != nil {
		return m.DurationMs
	}
	return 0
}

type SearchMetrics struct {
	InspectedTraces      uint32   `protobuf:"varint,1,opt,name=inspectedTraces,proto3" json:"inspectedTraces,omitempty"`
	InspectedBytes       uint64   `protobuf:"varint,2,opt,name=inspectedBytes,proto3" json:"inspectedBytes,omitempty"`
	InspectedBlocks      uint32   `protobuf:"varint,3,opt,name=inspectedBlocks,proto3" json:"inspectedBlocks,omitempty"`
	SkippedBlocks        uint32   `protobuf:"varint,4,opt,name=skippedBlocks,proto3" json:"skippedBlocks,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SearchMetrics) Reset()         { *m = SearchMetrics{} }
func (m *SearchMetrics) String() string { return proto.CompactTextString(m) }
func (*SearchMetrics) ProtoMessage()    {}
func (*SearchMetrics) Descriptor() ([]byte, []int) {
	return fileDescriptor_52a052455dcd7a1f, []int{7}
}
func (m *SearchMetrics) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SearchMetrics.Unmarshal(m, b)
}
func (m *SearchMetrics) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SearchMetrics.Marshal(b, m, deterministic)
}
func (m *SearchMetrics) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SearchMetrics.Merge(m, src)
}
func (m *SearchMetrics) XXX_Size() int {
	return xxx_messageInfo_SearchMetrics.Size(m)
}
func (m *SearchMetrics) XXX_DiscardUnknown() {
	xxx_messageInfo_SearchMetrics.DiscardUnknown(m)
}

var xxx_messageInfo_SearchMetrics proto.InternalMessageInfo

func (m *SearchMetrics) GetInspectedTraces() uint32 {
	if m != nil {
		return m.InspectedTraces
	}
	return 0
}

func (m *SearchMetrics) GetInspectedBytes() uint64 {
	if m != nil {
		return m.InspectedBytes
	}
	return 0
}

func (m *SearchMetrics) GetInspectedBlocks() uint32 {
	if m != nil {
		return m.InspectedBlocks
	}
	return 0
}

func (m *SearchMetrics) GetSkippedBlocks() uint32 {
	if m != nil {
		return m.SkippedBlocks
	}
	return 0
}

type SearchTagsRequest struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SearchTagsRequest) Reset()         { *m = SearchTagsRequest{} }
func (m *SearchTagsRequest) String() string { return proto.CompactTextString(m) }
func (*SearchTagsRequest) ProtoMessage()    {}
func (*SearchTagsRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_52a052455dcd7a1f, []int{8}
}
func (m *SearchTagsRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SearchTagsRequest.Unmarshal(m, b)
}
func (m *SearchTagsRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SearchTagsRequest.Marshal(b, m, deterministic)
}
func (m *SearchTagsRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SearchTagsRequest.Merge(m, src)
}
func (m *SearchTagsRequest) XXX_Size() int {
	return xxx_messageInfo_SearchTagsRequest.Size(m)
}
func (m *SearchTagsRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_SearchTagsRequest.DiscardUnknown(m)
}

var xxx_messageInfo_SearchTagsRequest proto.InternalMessageInfo

type SearchTagsResponse struct {
	TagNames             []string `protobuf:"bytes,1,rep,name=tagNames,proto3" json:"tagNames,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SearchTagsResponse) Reset()         { *m = SearchTagsResponse{} }
func (m *SearchTagsResponse) String() string { return proto.CompactTextString(m) }
func (*SearchTagsResponse) ProtoMessage()    {}
func (*SearchTagsResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_52a052455dcd7a1f, []int{9}
}
func (m *SearchTagsResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SearchTagsResponse.Unmarshal(m, b)
}
func (m *SearchTagsResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SearchTagsResponse.Marshal(b, m, deterministic)
}
func (m *SearchTagsResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SearchTagsResponse.Merge(m, src)
}
func (m *SearchTagsResponse) XXX_Size() int {
	return xxx_messageInfo_SearchTagsResponse.Size(m)
}
func (m *SearchTagsResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_SearchTagsResponse.DiscardUnknown(m)
}

var xxx_messageInfo_SearchTagsResponse proto.InternalMessageInfo

func (m *SearchTagsResponse) GetTagNames() []string {
	if m != nil {
		return m.TagNames
	}
	return nil
}

type SearchTagValuesRequest struct {
	TagName              string   `protobuf:"bytes,1,opt,name=tagName,proto3" json:"tagName,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SearchTagValuesRequest) Reset()         { *m = SearchTagValuesRequest{} }
func (m *SearchTagValuesRequest) String() string { return proto.CompactTextString(m) }
func (*SearchTagValuesRequest) ProtoMessage()    {}
func (*SearchTagValuesRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_52a052455dcd7a1f, []int{10}
}
func (m *SearchTagValuesRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SearchTagValuesRequest.Unmarshal(m, b)
}
func (m *SearchTagValuesRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SearchTagValuesRequest.Marshal(b, m, deterministic)
}
func (m *SearchTagValuesRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SearchTagValuesRequest.Merge(m, src)
}
func (m *SearchTagValuesRequest) XXX_Size() int {
	return xxx_messageInfo_SearchTagValuesRequest.Size(m)
}
func (m *SearchTagValuesRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_SearchTagValuesRequest.DiscardUnknown(m)
}

var xxx_messageInfo_SearchTagValuesRequest proto.InternalMessageInfo

func (m *SearchTagValuesRequest) GetTagName() string {
	if m != nil {
		return m.TagName
	}
	return ""
}

type SearchTagValuesResponse struct {
	TagValues            []string `protobuf:"bytes,1,rep,name=tagValues,proto3" json:"tagValues,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SearchTagValuesResponse) Reset()         { *m = SearchTagValuesResponse{} }
func (m *SearchTagValuesResponse) String() string { return proto.CompactTextString(m) }
func (*SearchTagValuesResponse) ProtoMessage()    {}
func (*SearchTagValuesResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_52a052455dcd7a1f, []int{11}
}
func (m *SearchTagValuesResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SearchTagValuesResponse.Unmarshal(m, b)
}
func (m *SearchTagValuesResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SearchTagValuesResponse.Marshal(b, m, deterministic)
}
func (m *SearchTagValuesResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SearchTagValuesResponse.Merge(m, src)
}
func (m *SearchTagValuesResponse) XXX_Size() int {
	return xxx_messageInfo_SearchTagValuesResponse.Size(m)
}
func (m *SearchTagValuesResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_SearchTagValuesResponse.DiscardUnknown(m)
}

var xxx_messageInfo_SearchTagValuesResponse proto.InternalMessageInfo

func (m *SearchTagValuesResponse) GetTagValues() []string {
	if m != nil {
		return m.TagValues
	}
	return nil
}

type Trace struct {
	Batches              []*v1.ResourceSpans `protobuf:"bytes,1,rep,name=batches,proto3" json:"batches,omitempty"`
	XXX_NoUnkeyedLiteral struct{}            `json:"-"`
	XXX_unrecognized     []byte              `json:"-"`
	XXX_sizecache        int32               `json:"-"`
}

func (m *Trace) Reset()         { *m = Trace{} }
func (m *Trace) String() string { return proto.CompactTextString(m) }
func (*Trace) ProtoMessage()    {}
func (*Trace) Descriptor() ([]byte, []int) {
	return fileDescriptor_52a052455dcd7a1f, []int{12}
}
func (m *Trace) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Trace.Unmarshal(m, b)
}
func (m *Trace) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Trace.Marshal(b, m, deterministic)
}
func (m *Trace) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Trace.Merge(m, src)
}
func (m *Trace) XXX_Size() int {
	return xxx_messageInfo_Trace.Size(m)
}
func (m *Trace) XXX_DiscardUnknown() {
	xxx_messageInfo_Trace.DiscardUnknown(m)
}

var xxx_messageInfo_Trace proto.InternalMessageInfo

func (m *Trace) GetBatches() []*v1.ResourceSpans {
	if m != nil {
		return m.Batches
	}
	return nil
}

// Write
type PushResponse struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *PushResponse) Reset()         { *m = PushResponse{} }
func (m *PushResponse) String() string { return proto.CompactTextString(m) }
func (*PushResponse) ProtoMessage()    {}
func (*PushResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_52a052455dcd7a1f, []int{13}
}
func (m *PushResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PushResponse.Unmarshal(m, b)
}
func (m *PushResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PushResponse.Marshal(b, m, deterministic)
}
func (m *PushResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PushResponse.Merge(m, src)
}
func (m *PushResponse) XXX_Size() int {
	return xxx_messageInfo_PushResponse.Size(m)
}
func (m *PushResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_PushResponse.DiscardUnknown(m)
}

var xxx_messageInfo_PushResponse proto.InternalMessageInfo

type PushBytesRequest struct {
	// pre-marshalled Traces. length must match ids
	Traces []PreallocBytes `protobuf:"bytes,2,rep,name=traces,proto3,customtype=PreallocBytes" json:"traces"`
	// trace ids. length must match traces
	Ids []PreallocBytes `protobuf:"bytes,3,rep,name=ids,proto3,customtype=PreallocBytes" json:"ids"`
	// search data, length must match traces
	SearchData           []PreallocBytes `protobuf:"bytes,4,rep,name=searchData,proto3,customtype=PreallocBytes" json:"searchData"`
	XXX_NoUnkeyedLiteral struct{}        `json:"-"`
	XXX_unrecognized     []byte          `json:"-"`
	XXX_sizecache        int32           `json:"-"`
}

func (m *PushBytesRequest) Reset()         { *m = PushBytesRequest{} }
func (m *PushBytesRequest) String() string { return proto.CompactTextString(m) }
func (*PushBytesRequest) ProtoMessage()    {}
func (*PushBytesRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_52a052455dcd7a1f, []int{14}
}
func (m *PushBytesRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PushBytesRequest.Unmarshal(m, b)
}
func (m *PushBytesRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PushBytesRequest.Marshal(b, m, deterministic)
}
func (m *PushBytesRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PushBytesRequest.Merge(m, src)
}
func (m *PushBytesRequest) XXX_Size() int {
	return xxx_messageInfo_PushBytesRequest.Size(m)
}
func (m *PushBytesRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_PushBytesRequest.DiscardUnknown(m)
}

var xxx_messageInfo_PushBytesRequest proto.InternalMessageInfo

type TraceBytes struct {
	// pre-marshalled Traces
	Traces               [][]byte `protobuf:"bytes,1,rep,name=traces,proto3" json:"traces,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *TraceBytes) Reset()         { *m = TraceBytes{} }
func (m *TraceBytes) String() string { return proto.CompactTextString(m) }
func (*TraceBytes) ProtoMessage()    {}
func (*TraceBytes) Descriptor() ([]byte, []int) {
	return fileDescriptor_52a052455dcd7a1f, []int{15}
}
func (m *TraceBytes) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_TraceBytes.Unmarshal(m, b)
}
func (m *TraceBytes) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_TraceBytes.Marshal(b, m, deterministic)
}
func (m *TraceBytes) XXX_Merge(src proto.Message) {
	xxx_messageInfo_TraceBytes.Merge(m, src)
}
func (m *TraceBytes) XXX_Size() int {
	return xxx_messageInfo_TraceBytes.Size(m)
}
func (m *TraceBytes) XXX_DiscardUnknown() {
	xxx_messageInfo_TraceBytes.DiscardUnknown(m)
}

var xxx_messageInfo_TraceBytes proto.InternalMessageInfo

func (m *TraceBytes) GetTraces() [][]byte {
	if m != nil {
		return m.Traces
	}
	return nil
}

func init() {
	proto.RegisterType((*TraceByIDRequest)(nil), "tempopb.TraceByIDRequest")
	proto.RegisterType((*TraceByIDResponse)(nil), "tempopb.TraceByIDResponse")
	proto.RegisterType((*TraceByIDMetrics)(nil), "tempopb.TraceByIDMetrics")
	proto.RegisterType((*SearchRequest)(nil), "tempopb.SearchRequest")
	proto.RegisterMapType((map[string]string)(nil), "tempopb.SearchRequest.TagsEntry")
	proto.RegisterType((*SearchBlockRequest)(nil), "tempopb.SearchBlockRequest")
	proto.RegisterType((*SearchResponse)(nil), "tempopb.SearchResponse")
	proto.RegisterType((*TraceSearchMetadata)(nil), "tempopb.TraceSearchMetadata")
	proto.RegisterType((*SearchMetrics)(nil), "tempopb.SearchMetrics")
	proto.RegisterType((*SearchTagsRequest)(nil), "tempopb.SearchTagsRequest")
	proto.RegisterType((*SearchTagsResponse)(nil), "tempopb.SearchTagsResponse")
	proto.RegisterType((*SearchTagValuesRequest)(nil), "tempopb.SearchTagValuesRequest")
	proto.RegisterType((*SearchTagValuesResponse)(nil), "tempopb.SearchTagValuesResponse")
	proto.RegisterType((*Trace)(nil), "tempopb.Trace")
	proto.RegisterType((*PushResponse)(nil), "tempopb.PushResponse")
	proto.RegisterType((*PushBytesRequest)(nil), "tempopb.PushBytesRequest")
	proto.RegisterType((*TraceBytes)(nil), "tempopb.TraceBytes")
}

func init() { proto.RegisterFile("tempo-idl/tempo.proto", fileDescriptor_52a052455dcd7a1f) }

var fileDescriptor_52a052455dcd7a1f = []byte{
	// 1011 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x7c, 0x55, 0x5d, 0x6e, 0xdb, 0x46,
	0x10, 0x8e, 0x7e, 0x6c, 0x99, 0x63, 0xc9, 0x3f, 0x9b, 0xd8, 0x61, 0x19, 0xa3, 0x16, 0x08, 0xa3,
	0x15, 0xd0, 0x5a, 0x4a, 0x94, 0xb4, 0x29, 0xf2, 0x52, 0x54, 0x90, 0xda, 0x1a, 0xa8, 0x0c, 0x97,
	0x52, 0xf3, 0xbe, 0x22, 0x37, 0xf2, 0xc2, 0x12, 0x97, 0x21, 0x57, 0x82, 0xd5, 0x03, 0xf4, 0xb1,
	0x77, 0xe8, 0x11, 0x7a, 0x8b, 0x3e, 0xb4, 0x17, 0xe8, 0x43, 0x8e, 0x52, 0x14, 0xfb, 0x47, 0x91,
	0x94, 0xe2, 0xb7, 0x9d, 0x6f, 0xbe, 0x9d, 0xdd, 0x99, 0xfd, 0x66, 0x16, 0x4e, 0x38, 0x99, 0x47,
	0xec, 0x92, 0x06, 0xb3, 0x8e, 0x5c, 0xb5, 0xa3, 0x98, 0x71, 0x86, 0x6a, 0xd2, 0x88, 0x26, 0xce,
	0x13, 0x1e, 0x63, 0x9f, 0x74, 0x96, 0x2f, 0x3a, 0x72, 0xa1, 0xdc, 0xce, 0xe5, 0x94, 0xf2, 0xdb,
	0xc5, 0xa4, 0xed, 0xb3, 0x79, 0x67, 0xca, 0xa6, 0xac, 0x23, 0xe1, 0xc9, 0xe2, 0x9d, 0xb4, 0xa4,
	0x21, 0x57, 0x8a, 0xee, 0xfe, 0x56, 0x82, 0xa3, 0xb1, 0xd8, 0xde, 0x5b, 0x5d, 0xf5, 0x3d, 0xf2,
	0x7e, 0x41, 0x12, 0x8e, 0x6c, 0xa8, 0xc9, 0x90, 0x57, 0x7d, 0xbb, 0xd4, 0x2c, 0xb5, 0xea, 0x9e,
	0x31, 0xd1, 0xa7, 0x00, 0x93, 0x19, 0xf3, 0xef, 0x46, 0x1c, 0xc7, 0xdc, 0x2e, 0x37, 0x4b, 0x2d,
	0xcb, 0xcb, 0x20, 0xc8, 0x81, 0x3d, 0x69, 0x0d, 0xc2, 0xc0, 0xae, 0x48, 0x6f, 0x6a, 0xa3, 0x33,
	0xb0, 0xde, 0x2f, 0x48, 0xbc, 0x1a, 0xb2, 0x80, 0xd8, 0x3b, 0xd2, 0xb9, 0x06, 0xdc, 0x10, 0x8e,
	0x33, 0xf7, 0x48, 0x22, 0x16, 0x26, 0x04, 0x5d, 0xc0, 0x8e, 0x3c, 0x59, 0x5e, 0x63, 0xbf, 0x7b,
	0xd0, 0xd6, 0xb9, 0xb7, 0x25, 0xd5, 0x53, 0x4e, 0xf4, 0x12, 0x6a, 0x73, 0xc2, 0x63, 0xea, 0x27,
	0xf2, 0x46, 0xfb, 0xdd, 0x4f, 0xf2, 0x3c, 0x11, 0x72, 0xa8, 0x08, 0x9e, 0x61, 0xba, 0x5f, 0x67,
	0xf2, 0xd6, 0x4e, 0xe4, 0x42, 0xfd, 0x1d, 0xa6, 0x33, 0x12, 0xf4, 0xc4, 0x9d, 0x13, 0x79, 0x6a,
	0xc3, 0xcb, 0x61, 0xee, 0xef, 0x65, 0x68, 0x8c, 0x08, 0x8e, 0xfd, 0x5b, 0x53, 0xad, 0x37, 0x50,
	0x1d, 0xe3, 0xa9, 0x60, 0x57, 0x5a, 0xfb, 0xdd, 0x66, 0x7a, 0x76, 0x8e, 0xd5, 0x16, 0x94, 0x41,
	0xc8, 0xe3, 0x55, 0xaf, 0xfa, 0xd7, 0x87, 0xf3, 0x47, 0x9e, 0xdc, 0x83, 0x2e, 0xa0, 0x31, 0xa4,
	0x61, 0x7f, 0x11, 0x63, 0x4e, 0x59, 0x38, 0x54, 0x09, 0x34, 0xbc, 0x3c, 0x28, 0x59, 0xf8, 0x3e,
	0xc3, 0xaa, 0x68, 0x56, 0x16, 0x44, 0x4f, 0x60, 0xe7, 0x27, 0x3a, 0xa7, 0xdc, 0xae, 0x4a, 0xaf,
	0x32, 0x04, 0x9a, 0xc8, 0xc7, 0xda, 0x51, 0xa8, 0x34, 0xd0, 0x11, 0x54, 0x48, 0x18, 0xd8, 0xbb,
	0x12, 0x13, 0x4b, 0xe7, 0x35, 0x58, 0xe9, 0x15, 0x85, 0xfb, 0x8e, 0xac, 0x64, 0xfe, 0x96, 0x27,
	0x96, 0x22, 0xcc, 0x12, 0xcf, 0x16, 0x44, 0xbf, 0xb9, 0x32, 0xde, 0x94, 0xbf, 0x29, 0xb9, 0x7f,
	0x97, 0x01, 0xa9, 0x54, 0x65, 0x85, 0x4c, 0x55, 0x5e, 0x81, 0x95, 0x98, 0x02, 0xe8, 0xe7, 0x3b,
	0xdd, 0x5e, 0x1a, 0x6f, 0x4d, 0x14, 0xca, 0x93, 0x7a, 0xb9, 0xea, 0xeb, 0x83, 0x8c, 0x29, 0xd4,
	0x23, 0xaf, 0x7e, 0x83, 0xa7, 0x44, 0xe7, 0xbf, 0x06, 0x44, 0x85, 0x22, 0x3c, 0x25, 0xc9, 0x98,
	0xa9, 0xd0, 0xba, 0x06, 0x79, 0x50, 0xa8, 0x93, 0x84, 0x3e, 0x0b, 0x68, 0x38, 0xd5, 0x02, 0x4c,
	0x6d, 0x11, 0x81, 0x86, 0x01, 0xb9, 0x17, 0xe1, 0x46, 0xf4, 0x57, 0xa2, 0x6b, 0x93, 0x07, 0x85,
	0x42, 0x38, 0xe3, 0x78, 0xe6, 0x11, 0x9f, 0xc5, 0x41, 0x62, 0xd7, 0x94, 0x42, 0xb2, 0x98, 0xe0,
	0x04, 0x98, 0xe3, 0x81, 0x39, 0x69, 0x4f, 0x9e, 0x94, 0xc3, 0x44, 0x9e, 0x4b, 0x12, 0x27, 0x94,
	0x85, 0xb6, 0xa5, 0xf2, 0xd4, 0xa6, 0x7b, 0x0f, 0x07, 0xa6, 0x3a, 0xba, 0x09, 0x5e, 0xc1, 0xae,
	0xd4, 0xb9, 0x51, 0xd8, 0x59, 0x5e, 0xdd, 0x8a, 0x3d, 0x24, 0x1c, 0x8b, 0x13, 0x3c, 0xcd, 0x45,
	0xcf, 0x8b, 0x4d, 0x51, 0xac, 0xfe, 0x46, 0x47, 0xfc, 0x53, 0x82, 0xc7, 0x5b, 0x22, 0x16, 0xa7,
	0x81, 0xb5, 0x9e, 0x06, 0x2d, 0x38, 0x8c, 0x19, 0xe3, 0x23, 0x12, 0x2f, 0xa9, 0x4f, 0xae, 0xf1,
	0xdc, 0xc8, 0xa3, 0x08, 0x8b, 0xea, 0x0a, 0x48, 0x86, 0x97, 0x3c, 0x35, 0x1c, 0xf2, 0x20, 0xfa,
	0x12, 0x8e, 0xe5, 0x93, 0x8e, 0xe9, 0x9c, 0xfc, 0x12, 0xd2, 0xfb, 0x6b, 0x1c, 0x32, 0xf9, 0x92,
	0x55, 0x6f, 0xd3, 0x21, 0x66, 0x51, 0xb0, 0x6e, 0x09, 0x25, 0xef, 0x0c, 0xe2, 0xfe, 0x59, 0x32,
	0x9d, 0x6a, 0xfa, 0xbb, 0x05, 0x87, 0x34, 0x4c, 0x22, 0xe2, 0x73, 0x12, 0x8c, 0x4d, 0x49, 0xc5,
	0xb6, 0x22, 0x8c, 0x3e, 0x83, 0x83, 0x14, 0xea, 0xad, 0x38, 0x51, 0x45, 0xac, 0x7a, 0x05, 0x34,
	0x17, 0x51, 0x0f, 0x8d, 0x4a, 0x21, 0xa2, 0x82, 0x45, 0x05, 0x92, 0x3b, 0x1a, 0x45, 0x29, 0x4f,
	0x2b, 0x34, 0x07, 0xba, 0x8f, 0xe1, 0x58, 0x5d, 0x59, 0xf4, 0xa2, 0xee, 0x0f, 0xf7, 0xb9, 0x69,
	0x30, 0x05, 0x6a, 0x59, 0x38, 0xb0, 0xc7, 0xf1, 0x54, 0xd4, 0x4d, 0x09, 0xc3, 0xf2, 0x52, 0xdb,
	0xed, 0xc2, 0x69, 0xba, 0xe3, 0xad, 0xe8, 0xd4, 0x24, 0x3b, 0xda, 0x15, 0x2b, 0x7d, 0x4c, 0x65,
	0xba, 0xaf, 0xe1, 0xe9, 0xc6, 0x1e, 0x7d, 0xd4, 0x19, 0x58, 0xdc, 0x80, 0xfa, 0xac, 0x35, 0xe0,
	0x5e, 0xc3, 0x8e, 0xac, 0x1a, 0x1a, 0x40, 0x6d, 0x82, 0xb9, 0x7f, 0x9b, 0x2a, 0xf5, 0x8b, 0x36,
	0x8b, 0x48, 0xc8, 0xc9, 0x8c, 0x08, 0x8d, 0xad, 0xd4, 0x97, 0xd3, 0x56, 0xbf, 0xd5, 0xf2, 0x45,
	0xdb, 0x23, 0x09, 0x5b, 0xc4, 0x3e, 0x19, 0x45, 0x38, 0x4c, 0x3c, 0xb3, 0xd7, 0x3d, 0x80, 0xfa,
	0xcd, 0x22, 0x49, 0xf5, 0xef, 0xfe, 0x51, 0x82, 0x23, 0x01, 0xc8, 0x8a, 0x9b, 0x3c, 0x2e, 0xd3,
	0xa6, 0x28, 0x37, 0x2b, 0xad, 0x7a, 0xef, 0x44, 0x0c, 0xd5, 0x7f, 0x3f, 0x9c, 0x37, 0x6e, 0x62,
	0x82, 0x67, 0x33, 0xe6, 0x2b, 0xb6, 0xe9, 0x86, 0xcf, 0xa1, 0x42, 0x03, 0xf1, 0x36, 0x0f, 0x70,
	0x05, 0x03, 0x7d, 0x05, 0xa0, 0xa6, 0x51, 0x1f, 0x73, 0x6c, 0x57, 0x1f, 0xe2, 0x67, 0x88, 0xee,
	0x05, 0x80, 0xfe, 0x4d, 0x84, 0x2a, 0x4e, 0x73, 0x1d, 0x5b, 0x37, 0xb7, 0xe8, 0x5e, 0xc1, 0xae,
	0x48, 0x84, 0xc4, 0xe8, 0x5b, 0xb0, 0xd2, 0x94, 0xd0, 0xfa, 0xbb, 0x2a, 0xa6, 0xe9, 0x9c, 0xe4,
	0x5c, 0x69, 0x49, 0x1e, 0x75, 0xff, 0x2b, 0x43, 0xed, 0xe7, 0x05, 0x89, 0x29, 0x89, 0xd1, 0x8f,
	0xd0, 0xf8, 0x9e, 0x86, 0x41, 0xfa, 0x9d, 0xa1, 0x2d, 0xff, 0x9f, 0x09, 0xe8, 0x6c, 0x73, 0x99,
	0xa8, 0xe8, 0x3b, 0xa8, 0x9b, 0xe1, 0xe3, 0x93, 0x90, 0xa3, 0x8f, 0x4c, 0x6c, 0xe7, 0xe9, 0x06,
	0x9e, 0x86, 0x18, 0xc0, 0x7e, 0xe6, 0x37, 0x40, 0xcf, 0x0a, 0xcc, 0xec, 0x1f, 0xf1, 0x50, 0x98,
	0x1f, 0x00, 0xd6, 0x9a, 0x47, 0x4e, 0x81, 0x98, 0xe9, 0x0e, 0xe7, 0xd9, 0x56, 0x5f, 0x1a, 0xe8,
	0x2d, 0x1c, 0x16, 0x64, 0x8d, 0xce, 0x37, 0x77, 0xe4, 0x9a, 0xc4, 0x69, 0x7e, 0x9c, 0x60, 0xe2,
	0x4e, 0x76, 0xa5, 0x98, 0x5f, 0xfe, 0x1f, 0x00, 0x00, 0xff, 0xff, 0xe5, 0x88, 0x05, 0xbc, 0xa6,
	0x09, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// PusherClient is the client API for Pusher service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type PusherClient interface {
	PushBytes(ctx context.Context, in *PushBytesRequest, opts ...grpc.CallOption) (*PushResponse, error)
}

type pusherClient struct {
	cc *grpc.ClientConn
}

func NewPusherClient(cc *grpc.ClientConn) PusherClient {
	return &pusherClient{cc}
}

func (c *pusherClient) PushBytes(ctx context.Context, in *PushBytesRequest, opts ...grpc.CallOption) (*PushResponse, error) {
	out := new(PushResponse)
	err := c.cc.Invoke(ctx, "/tempopb.Pusher/PushBytes", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// PusherServer is the server API for Pusher service.
type PusherServer interface {
	PushBytes(context.Context, *PushBytesRequest) (*PushResponse, error)
}

// UnimplementedPusherServer can be embedded to have forward compatible implementations.
type UnimplementedPusherServer struct {
}

func (*UnimplementedPusherServer) PushBytes(ctx context.Context, req *PushBytesRequest) (*PushResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method PushBytes not implemented")
}

func RegisterPusherServer(s *grpc.Server, srv PusherServer) {
	s.RegisterService(&_Pusher_serviceDesc, srv)
}

func _Pusher_PushBytes_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PushBytesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PusherServer).PushBytes(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/tempopb.Pusher/PushBytes",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PusherServer).PushBytes(ctx, req.(*PushBytesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _Pusher_serviceDesc = grpc.ServiceDesc{
	ServiceName: "tempopb.Pusher",
	HandlerType: (*PusherServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "PushBytes",
			Handler:    _Pusher_PushBytes_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "tempo-idl/tempo.proto",
}

// QuerierClient is the client API for Querier service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type QuerierClient interface {
	FindTraceByID(ctx context.Context, in *TraceByIDRequest, opts ...grpc.CallOption) (*TraceByIDResponse, error)
	SearchRecent(ctx context.Context, in *SearchRequest, opts ...grpc.CallOption) (*SearchResponse, error)
	SearchBlock(ctx context.Context, in *SearchBlockRequest, opts ...grpc.CallOption) (*SearchResponse, error)
	SearchTags(ctx context.Context, in *SearchTagsRequest, opts ...grpc.CallOption) (*SearchTagsResponse, error)
	SearchTagValues(ctx context.Context, in *SearchTagValuesRequest, opts ...grpc.CallOption) (*SearchTagValuesResponse, error)
}

type querierClient struct {
	cc *grpc.ClientConn
}

func NewQuerierClient(cc *grpc.ClientConn) QuerierClient {
	return &querierClient{cc}
}

func (c *querierClient) FindTraceByID(ctx context.Context, in *TraceByIDRequest, opts ...grpc.CallOption) (*TraceByIDResponse, error) {
	out := new(TraceByIDResponse)
	err := c.cc.Invoke(ctx, "/tempopb.Querier/FindTraceByID", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *querierClient) SearchRecent(ctx context.Context, in *SearchRequest, opts ...grpc.CallOption) (*SearchResponse, error) {
	out := new(SearchResponse)
	err := c.cc.Invoke(ctx, "/tempopb.Querier/SearchRecent", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *querierClient) SearchBlock(ctx context.Context, in *SearchBlockRequest, opts ...grpc.CallOption) (*SearchResponse, error) {
	out := new(SearchResponse)
	err := c.cc.Invoke(ctx, "/tempopb.Querier/SearchBlock", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *querierClient) SearchTags(ctx context.Context, in *SearchTagsRequest, opts ...grpc.CallOption) (*SearchTagsResponse, error) {
	out := new(SearchTagsResponse)
	err := c.cc.Invoke(ctx, "/tempopb.Querier/SearchTags", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *querierClient) SearchTagValues(ctx context.Context, in *SearchTagValuesRequest, opts ...grpc.CallOption) (*SearchTagValuesResponse, error) {
	out := new(SearchTagValuesResponse)
	err := c.cc.Invoke(ctx, "/tempopb.Querier/SearchTagValues", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// QuerierServer is the server API for Querier service.
type QuerierServer interface {
	FindTraceByID(context.Context, *TraceByIDRequest) (*TraceByIDResponse, error)
	SearchRecent(context.Context, *SearchRequest) (*SearchResponse, error)
	SearchBlock(context.Context, *SearchBlockRequest) (*SearchResponse, error)
	SearchTags(context.Context, *SearchTagsRequest) (*SearchTagsResponse, error)
	SearchTagValues(context.Context, *SearchTagValuesRequest) (*SearchTagValuesResponse, error)
}

// UnimplementedQuerierServer can be embedded to have forward compatible implementations.
type UnimplementedQuerierServer struct {
}

func (*UnimplementedQuerierServer) FindTraceByID(ctx context.Context, req *TraceByIDRequest) (*TraceByIDResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method FindTraceByID not implemented")
}
func (*UnimplementedQuerierServer) SearchRecent(ctx context.Context, req *SearchRequest) (*SearchResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SearchRecent not implemented")
}
func (*UnimplementedQuerierServer) SearchBlock(ctx context.Context, req *SearchBlockRequest) (*SearchResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SearchBlock not implemented")
}
func (*UnimplementedQuerierServer) SearchTags(ctx context.Context, req *SearchTagsRequest) (*SearchTagsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SearchTags not implemented")
}
func (*UnimplementedQuerierServer) SearchTagValues(ctx context.Context, req *SearchTagValuesRequest) (*SearchTagValuesResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SearchTagValues not implemented")
}

func RegisterQuerierServer(s *grpc.Server, srv QuerierServer) {
	s.RegisterService(&_Querier_serviceDesc, srv)
}

func _Querier_FindTraceByID_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(TraceByIDRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(QuerierServer).FindTraceByID(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/tempopb.Querier/FindTraceByID",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(QuerierServer).FindTraceByID(ctx, req.(*TraceByIDRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Querier_SearchRecent_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SearchRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(QuerierServer).SearchRecent(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/tempopb.Querier/SearchRecent",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(QuerierServer).SearchRecent(ctx, req.(*SearchRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Querier_SearchBlock_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SearchBlockRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(QuerierServer).SearchBlock(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/tempopb.Querier/SearchBlock",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(QuerierServer).SearchBlock(ctx, req.(*SearchBlockRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Querier_SearchTags_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SearchTagsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(QuerierServer).SearchTags(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/tempopb.Querier/SearchTags",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(QuerierServer).SearchTags(ctx, req.(*SearchTagsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Querier_SearchTagValues_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SearchTagValuesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(QuerierServer).SearchTagValues(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/tempopb.Querier/SearchTagValues",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(QuerierServer).SearchTagValues(ctx, req.(*SearchTagValuesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _Querier_serviceDesc = grpc.ServiceDesc{
	ServiceName: "tempopb.Querier",
	HandlerType: (*QuerierServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "FindTraceByID",
			Handler:    _Querier_FindTraceByID_Handler,
		},
		{
			MethodName: "SearchRecent",
			Handler:    _Querier_SearchRecent_Handler,
		},
		{
			MethodName: "SearchBlock",
			Handler:    _Querier_SearchBlock_Handler,
		},
		{
			MethodName: "SearchTags",
			Handler:    _Querier_SearchTags_Handler,
		},
		{
			MethodName: "SearchTagValues",
			Handler:    _Querier_SearchTagValues_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "tempo-idl/tempo.proto",
}
