/*
TraceTest

OpenAPI definition for TraceTest endpoint and resources

API version: 0.2.1
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
)

// checks if the HTTPRequest type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &HTTPRequest{}

// HTTPRequest struct for HTTPRequest
type HTTPRequest struct {
	Url             *string      `json:"url,omitempty"`
	Method          *string      `json:"method,omitempty"`
	Headers         []HTTPHeader `json:"headers,omitempty"`
	Body            *string      `json:"body,omitempty"`
	Auth            *HTTPAuth    `json:"auth,omitempty"`
	SslVerification *bool        `json:"sslVerification,omitempty"`
}

// NewHTTPRequest instantiates a new HTTPRequest object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewHTTPRequest() *HTTPRequest {
	this := HTTPRequest{}
	var sslVerification bool = false
	this.SslVerification = &sslVerification
	return &this
}

// NewHTTPRequestWithDefaults instantiates a new HTTPRequest object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewHTTPRequestWithDefaults() *HTTPRequest {
	this := HTTPRequest{}
	var sslVerification bool = false
	this.SslVerification = &sslVerification
	return &this
}

// GetUrl returns the Url field value if set, zero value otherwise.
func (o *HTTPRequest) GetUrl() string {
	if o == nil || isNil(o.Url) {
		var ret string
		return ret
	}
	return *o.Url
}

// GetUrlOk returns a tuple with the Url field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *HTTPRequest) GetUrlOk() (*string, bool) {
	if o == nil || isNil(o.Url) {
		return nil, false
	}
	return o.Url, true
}

// HasUrl returns a boolean if a field has been set.
func (o *HTTPRequest) HasUrl() bool {
	if o != nil && !isNil(o.Url) {
		return true
	}

	return false
}

// SetUrl gets a reference to the given string and assigns it to the Url field.
func (o *HTTPRequest) SetUrl(v string) {
	o.Url = &v
}

// GetMethod returns the Method field value if set, zero value otherwise.
func (o *HTTPRequest) GetMethod() string {
	if o == nil || isNil(o.Method) {
		var ret string
		return ret
	}
	return *o.Method
}

// GetMethodOk returns a tuple with the Method field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *HTTPRequest) GetMethodOk() (*string, bool) {
	if o == nil || isNil(o.Method) {
		return nil, false
	}
	return o.Method, true
}

// HasMethod returns a boolean if a field has been set.
func (o *HTTPRequest) HasMethod() bool {
	if o != nil && !isNil(o.Method) {
		return true
	}

	return false
}

// SetMethod gets a reference to the given string and assigns it to the Method field.
func (o *HTTPRequest) SetMethod(v string) {
	o.Method = &v
}

// GetHeaders returns the Headers field value if set, zero value otherwise.
func (o *HTTPRequest) GetHeaders() []HTTPHeader {
	if o == nil || isNil(o.Headers) {
		var ret []HTTPHeader
		return ret
	}
	return o.Headers
}

// GetHeadersOk returns a tuple with the Headers field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *HTTPRequest) GetHeadersOk() ([]HTTPHeader, bool) {
	if o == nil || isNil(o.Headers) {
		return nil, false
	}
	return o.Headers, true
}

// HasHeaders returns a boolean if a field has been set.
func (o *HTTPRequest) HasHeaders() bool {
	if o != nil && !isNil(o.Headers) {
		return true
	}

	return false
}

// SetHeaders gets a reference to the given []HTTPHeader and assigns it to the Headers field.
func (o *HTTPRequest) SetHeaders(v []HTTPHeader) {
	o.Headers = v
}

// GetBody returns the Body field value if set, zero value otherwise.
func (o *HTTPRequest) GetBody() string {
	if o == nil || isNil(o.Body) {
		var ret string
		return ret
	}
	return *o.Body
}

// GetBodyOk returns a tuple with the Body field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *HTTPRequest) GetBodyOk() (*string, bool) {
	if o == nil || isNil(o.Body) {
		return nil, false
	}
	return o.Body, true
}

// HasBody returns a boolean if a field has been set.
func (o *HTTPRequest) HasBody() bool {
	if o != nil && !isNil(o.Body) {
		return true
	}

	return false
}

// SetBody gets a reference to the given string and assigns it to the Body field.
func (o *HTTPRequest) SetBody(v string) {
	o.Body = &v
}

// GetAuth returns the Auth field value if set, zero value otherwise.
func (o *HTTPRequest) GetAuth() HTTPAuth {
	if o == nil || isNil(o.Auth) {
		var ret HTTPAuth
		return ret
	}
	return *o.Auth
}

// GetAuthOk returns a tuple with the Auth field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *HTTPRequest) GetAuthOk() (*HTTPAuth, bool) {
	if o == nil || isNil(o.Auth) {
		return nil, false
	}
	return o.Auth, true
}

// HasAuth returns a boolean if a field has been set.
func (o *HTTPRequest) HasAuth() bool {
	if o != nil && !isNil(o.Auth) {
		return true
	}

	return false
}

// SetAuth gets a reference to the given HTTPAuth and assigns it to the Auth field.
func (o *HTTPRequest) SetAuth(v HTTPAuth) {
	o.Auth = &v
}

// GetSslVerification returns the SslVerification field value if set, zero value otherwise.
func (o *HTTPRequest) GetSslVerification() bool {
	if o == nil || isNil(o.SslVerification) {
		var ret bool
		return ret
	}
	return *o.SslVerification
}

// GetSslVerificationOk returns a tuple with the SslVerification field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *HTTPRequest) GetSslVerificationOk() (*bool, bool) {
	if o == nil || isNil(o.SslVerification) {
		return nil, false
	}
	return o.SslVerification, true
}

// HasSslVerification returns a boolean if a field has been set.
func (o *HTTPRequest) HasSslVerification() bool {
	if o != nil && !isNil(o.SslVerification) {
		return true
	}

	return false
}

// SetSslVerification gets a reference to the given bool and assigns it to the SslVerification field.
func (o *HTTPRequest) SetSslVerification(v bool) {
	o.SslVerification = &v
}

func (o HTTPRequest) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o HTTPRequest) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !isNil(o.Url) {
		toSerialize["url"] = o.Url
	}
	if !isNil(o.Method) {
		toSerialize["method"] = o.Method
	}
	if !isNil(o.Headers) {
		toSerialize["headers"] = o.Headers
	}
	if !isNil(o.Body) {
		toSerialize["body"] = o.Body
	}
	if !isNil(o.Auth) {
		toSerialize["auth"] = o.Auth
	}
	if !isNil(o.SslVerification) {
		toSerialize["sslVerification"] = o.SslVerification
	}
	return toSerialize, nil
}

type NullableHTTPRequest struct {
	value *HTTPRequest
	isSet bool
}

func (v NullableHTTPRequest) Get() *HTTPRequest {
	return v.value
}

func (v *NullableHTTPRequest) Set(val *HTTPRequest) {
	v.value = val
	v.isSet = true
}

func (v NullableHTTPRequest) IsSet() bool {
	return v.isSet
}

func (v *NullableHTTPRequest) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableHTTPRequest(val *HTTPRequest) *NullableHTTPRequest {
	return &NullableHTTPRequest{value: val, isSet: true}
}

func (v NullableHTTPRequest) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableHTTPRequest) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
