/*
TraceTest

OpenAPI definition for TraceTest endpoint and resources

API version: 0.2.1
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
)

// checks if the GetMonitorRuns200Response type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &GetMonitorRuns200Response{}

// GetMonitorRuns200Response struct for GetMonitorRuns200Response
type GetMonitorRuns200Response struct {
	Items []MonitorRun `json:"items,omitempty"`
	Count *int32       `json:"count,omitempty"`
}

// NewGetMonitorRuns200Response instantiates a new GetMonitorRuns200Response object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewGetMonitorRuns200Response() *GetMonitorRuns200Response {
	this := GetMonitorRuns200Response{}
	return &this
}

// NewGetMonitorRuns200ResponseWithDefaults instantiates a new GetMonitorRuns200Response object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewGetMonitorRuns200ResponseWithDefaults() *GetMonitorRuns200Response {
	this := GetMonitorRuns200Response{}
	return &this
}

// GetItems returns the Items field value if set, zero value otherwise.
func (o *GetMonitorRuns200Response) GetItems() []MonitorRun {
	if o == nil || isNil(o.Items) {
		var ret []MonitorRun
		return ret
	}
	return o.Items
}

// GetItemsOk returns a tuple with the Items field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GetMonitorRuns200Response) GetItemsOk() ([]MonitorRun, bool) {
	if o == nil || isNil(o.Items) {
		return nil, false
	}
	return o.Items, true
}

// HasItems returns a boolean if a field has been set.
func (o *GetMonitorRuns200Response) HasItems() bool {
	if o != nil && !isNil(o.Items) {
		return true
	}

	return false
}

// SetItems gets a reference to the given []MonitorRun and assigns it to the Items field.
func (o *GetMonitorRuns200Response) SetItems(v []MonitorRun) {
	o.Items = v
}

// GetCount returns the Count field value if set, zero value otherwise.
func (o *GetMonitorRuns200Response) GetCount() int32 {
	if o == nil || isNil(o.Count) {
		var ret int32
		return ret
	}
	return *o.Count
}

// GetCountOk returns a tuple with the Count field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GetMonitorRuns200Response) GetCountOk() (*int32, bool) {
	if o == nil || isNil(o.Count) {
		return nil, false
	}
	return o.Count, true
}

// HasCount returns a boolean if a field has been set.
func (o *GetMonitorRuns200Response) HasCount() bool {
	if o != nil && !isNil(o.Count) {
		return true
	}

	return false
}

// SetCount gets a reference to the given int32 and assigns it to the Count field.
func (o *GetMonitorRuns200Response) SetCount(v int32) {
	o.Count = &v
}

func (o GetMonitorRuns200Response) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o GetMonitorRuns200Response) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !isNil(o.Items) {
		toSerialize["items"] = o.Items
	}
	if !isNil(o.Count) {
		toSerialize["count"] = o.Count
	}
	return toSerialize, nil
}

type NullableGetMonitorRuns200Response struct {
	value *GetMonitorRuns200Response
	isSet bool
}

func (v NullableGetMonitorRuns200Response) Get() *GetMonitorRuns200Response {
	return v.value
}

func (v *NullableGetMonitorRuns200Response) Set(val *GetMonitorRuns200Response) {
	v.value = val
	v.isSet = true
}

func (v NullableGetMonitorRuns200Response) IsSet() bool {
	return v.isSet
}

func (v *NullableGetMonitorRuns200Response) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableGetMonitorRuns200Response(val *GetMonitorRuns200Response) *NullableGetMonitorRuns200Response {
	return &NullableGetMonitorRuns200Response{value: val, isSet: true}
}

func (v NullableGetMonitorRuns200Response) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableGetMonitorRuns200Response) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
