/*
TraceTest

OpenAPI definition for TraceTest endpoint and resources

API version: 0.2.1
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
)

// checks if the TestResource type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &TestResource{}

// TestResource Represents a test structured into the Resources format.
type TestResource struct {
	// Represents the type of this resource. It should always be set as 'Test'.
	Type *string `json:"type,omitempty"`
	Spec *Test   `json:"spec,omitempty"`
}

// NewTestResource instantiates a new TestResource object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewTestResource() *TestResource {
	this := TestResource{}
	return &this
}

// NewTestResourceWithDefaults instantiates a new TestResource object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewTestResourceWithDefaults() *TestResource {
	this := TestResource{}
	return &this
}

// GetType returns the Type field value if set, zero value otherwise.
func (o *TestResource) GetType() string {
	if o == nil || isNil(o.Type) {
		var ret string
		return ret
	}
	return *o.Type
}

// GetTypeOk returns a tuple with the Type field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *TestResource) GetTypeOk() (*string, bool) {
	if o == nil || isNil(o.Type) {
		return nil, false
	}
	return o.Type, true
}

// HasType returns a boolean if a field has been set.
func (o *TestResource) HasType() bool {
	if o != nil && !isNil(o.Type) {
		return true
	}

	return false
}

// SetType gets a reference to the given string and assigns it to the Type field.
func (o *TestResource) SetType(v string) {
	o.Type = &v
}

// GetSpec returns the Spec field value if set, zero value otherwise.
func (o *TestResource) GetSpec() Test {
	if o == nil || isNil(o.Spec) {
		var ret Test
		return ret
	}
	return *o.Spec
}

// GetSpecOk returns a tuple with the Spec field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *TestResource) GetSpecOk() (*Test, bool) {
	if o == nil || isNil(o.Spec) {
		return nil, false
	}
	return o.Spec, true
}

// HasSpec returns a boolean if a field has been set.
func (o *TestResource) HasSpec() bool {
	if o != nil && !isNil(o.Spec) {
		return true
	}

	return false
}

// SetSpec gets a reference to the given Test and assigns it to the Spec field.
func (o *TestResource) SetSpec(v Test) {
	o.Spec = &v
}

func (o TestResource) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o TestResource) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !isNil(o.Type) {
		toSerialize["type"] = o.Type
	}
	if !isNil(o.Spec) {
		toSerialize["spec"] = o.Spec
	}
	return toSerialize, nil
}

type NullableTestResource struct {
	value *TestResource
	isSet bool
}

func (v NullableTestResource) Get() *TestResource {
	return v.value
}

func (v *NullableTestResource) Set(val *TestResource) {
	v.value = val
	v.isSet = true
}

func (v NullableTestResource) IsSet() bool {
	return v.isSet
}

func (v *NullableTestResource) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableTestResource(val *TestResource) *NullableTestResource {
	return &NullableTestResource{value: val, isSet: true}
}

func (v NullableTestResource) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableTestResource) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
