/*
TraceTest

OpenAPI definition for TraceTest endpoint and resources

API version: 0.2.1
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
)

// checks if the PollingProfileList type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &PollingProfileList{}

// PollingProfileList struct for PollingProfileList
type PollingProfileList struct {
	Count *int32           `json:"count,omitempty"`
	Items []PollingProfile `json:"items,omitempty"`
}

// NewPollingProfileList instantiates a new PollingProfileList object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewPollingProfileList() *PollingProfileList {
	this := PollingProfileList{}
	return &this
}

// NewPollingProfileListWithDefaults instantiates a new PollingProfileList object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewPollingProfileListWithDefaults() *PollingProfileList {
	this := PollingProfileList{}
	return &this
}

// GetCount returns the Count field value if set, zero value otherwise.
func (o *PollingProfileList) GetCount() int32 {
	if o == nil || isNil(o.Count) {
		var ret int32
		return ret
	}
	return *o.Count
}

// GetCountOk returns a tuple with the Count field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *PollingProfileList) GetCountOk() (*int32, bool) {
	if o == nil || isNil(o.Count) {
		return nil, false
	}
	return o.Count, true
}

// HasCount returns a boolean if a field has been set.
func (o *PollingProfileList) HasCount() bool {
	if o != nil && !isNil(o.Count) {
		return true
	}

	return false
}

// SetCount gets a reference to the given int32 and assigns it to the Count field.
func (o *PollingProfileList) SetCount(v int32) {
	o.Count = &v
}

// GetItems returns the Items field value if set, zero value otherwise.
func (o *PollingProfileList) GetItems() []PollingProfile {
	if o == nil || isNil(o.Items) {
		var ret []PollingProfile
		return ret
	}
	return o.Items
}

// GetItemsOk returns a tuple with the Items field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *PollingProfileList) GetItemsOk() ([]PollingProfile, bool) {
	if o == nil || isNil(o.Items) {
		return nil, false
	}
	return o.Items, true
}

// HasItems returns a boolean if a field has been set.
func (o *PollingProfileList) HasItems() bool {
	if o != nil && !isNil(o.Items) {
		return true
	}

	return false
}

// SetItems gets a reference to the given []PollingProfile and assigns it to the Items field.
func (o *PollingProfileList) SetItems(v []PollingProfile) {
	o.Items = v
}

func (o PollingProfileList) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o PollingProfileList) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !isNil(o.Count) {
		toSerialize["count"] = o.Count
	}
	if !isNil(o.Items) {
		toSerialize["items"] = o.Items
	}
	return toSerialize, nil
}

type NullablePollingProfileList struct {
	value *PollingProfileList
	isSet bool
}

func (v NullablePollingProfileList) Get() *PollingProfileList {
	return v.value
}

func (v *NullablePollingProfileList) Set(val *PollingProfileList) {
	v.value = val
	v.isSet = true
}

func (v NullablePollingProfileList) IsSet() bool {
	return v.isSet
}

func (v *NullablePollingProfileList) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullablePollingProfileList(val *PollingProfileList) *NullablePollingProfileList {
	return &NullablePollingProfileList{value: val, isSet: true}
}

func (v NullablePollingProfileList) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullablePollingProfileList) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
