/*
TraceTest

OpenAPI definition for TraceTest endpoint and resources

API version: 0.2.1
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
)

// checks if the EnvironmentResource type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &EnvironmentResource{}

// EnvironmentResource Represents an environment structured into the Resources format.
type EnvironmentResource struct {
	// Represents the type of this resource. It should always be set as 'Environment'.
	Type *string      `json:"type,omitempty"`
	Spec *Environment `json:"spec,omitempty"`
}

// NewEnvironmentResource instantiates a new EnvironmentResource object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewEnvironmentResource() *EnvironmentResource {
	this := EnvironmentResource{}
	return &this
}

// NewEnvironmentResourceWithDefaults instantiates a new EnvironmentResource object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewEnvironmentResourceWithDefaults() *EnvironmentResource {
	this := EnvironmentResource{}
	return &this
}

// GetType returns the Type field value if set, zero value otherwise.
func (o *EnvironmentResource) GetType() string {
	if o == nil || isNil(o.Type) {
		var ret string
		return ret
	}
	return *o.Type
}

// GetTypeOk returns a tuple with the Type field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *EnvironmentResource) GetTypeOk() (*string, bool) {
	if o == nil || isNil(o.Type) {
		return nil, false
	}
	return o.Type, true
}

// HasType returns a boolean if a field has been set.
func (o *EnvironmentResource) HasType() bool {
	if o != nil && !isNil(o.Type) {
		return true
	}

	return false
}

// SetType gets a reference to the given string and assigns it to the Type field.
func (o *EnvironmentResource) SetType(v string) {
	o.Type = &v
}

// GetSpec returns the Spec field value if set, zero value otherwise.
func (o *EnvironmentResource) GetSpec() Environment {
	if o == nil || isNil(o.Spec) {
		var ret Environment
		return ret
	}
	return *o.Spec
}

// GetSpecOk returns a tuple with the Spec field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *EnvironmentResource) GetSpecOk() (*Environment, bool) {
	if o == nil || isNil(o.Spec) {
		return nil, false
	}
	return o.Spec, true
}

// HasSpec returns a boolean if a field has been set.
func (o *EnvironmentResource) HasSpec() bool {
	if o != nil && !isNil(o.Spec) {
		return true
	}

	return false
}

// SetSpec gets a reference to the given Environment and assigns it to the Spec field.
func (o *EnvironmentResource) SetSpec(v Environment) {
	o.Spec = &v
}

func (o EnvironmentResource) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o EnvironmentResource) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !isNil(o.Type) {
		toSerialize["type"] = o.Type
	}
	if !isNil(o.Spec) {
		toSerialize["spec"] = o.Spec
	}
	return toSerialize, nil
}

type NullableEnvironmentResource struct {
	value *EnvironmentResource
	isSet bool
}

func (v NullableEnvironmentResource) Get() *EnvironmentResource {
	return v.value
}

func (v *NullableEnvironmentResource) Set(val *EnvironmentResource) {
	v.value = val
	v.isSet = true
}

func (v NullableEnvironmentResource) IsSet() bool {
	return v.isSet
}

func (v *NullableEnvironmentResource) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableEnvironmentResource(val *EnvironmentResource) *NullableEnvironmentResource {
	return &NullableEnvironmentResource{value: val, isSet: true}
}

func (v NullableEnvironmentResource) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableEnvironmentResource) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
