/*
TraceTest

OpenAPI definition for TraceTest endpoint and resources

API version: 0.2.1
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
)

// checks if the LinterResourceSpec type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &LinterResourceSpec{}

// LinterResourceSpec struct for LinterResourceSpec
type LinterResourceSpec struct {
	Id           *string                `json:"id,omitempty"`
	Name         *string                `json:"name,omitempty"`
	Enabled      *bool                  `json:"enabled,omitempty"`
	MinimumScore *int32                 `json:"minimumScore,omitempty"`
	Plugins      []LinterResourcePlugin `json:"plugins,omitempty"`
}

// NewLinterResourceSpec instantiates a new LinterResourceSpec object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewLinterResourceSpec() *LinterResourceSpec {
	this := LinterResourceSpec{}
	return &this
}

// NewLinterResourceSpecWithDefaults instantiates a new LinterResourceSpec object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewLinterResourceSpecWithDefaults() *LinterResourceSpec {
	this := LinterResourceSpec{}
	return &this
}

// GetId returns the Id field value if set, zero value otherwise.
func (o *LinterResourceSpec) GetId() string {
	if o == nil || isNil(o.Id) {
		var ret string
		return ret
	}
	return *o.Id
}

// GetIdOk returns a tuple with the Id field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *LinterResourceSpec) GetIdOk() (*string, bool) {
	if o == nil || isNil(o.Id) {
		return nil, false
	}
	return o.Id, true
}

// HasId returns a boolean if a field has been set.
func (o *LinterResourceSpec) HasId() bool {
	if o != nil && !isNil(o.Id) {
		return true
	}

	return false
}

// SetId gets a reference to the given string and assigns it to the Id field.
func (o *LinterResourceSpec) SetId(v string) {
	o.Id = &v
}

// GetName returns the Name field value if set, zero value otherwise.
func (o *LinterResourceSpec) GetName() string {
	if o == nil || isNil(o.Name) {
		var ret string
		return ret
	}
	return *o.Name
}

// GetNameOk returns a tuple with the Name field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *LinterResourceSpec) GetNameOk() (*string, bool) {
	if o == nil || isNil(o.Name) {
		return nil, false
	}
	return o.Name, true
}

// HasName returns a boolean if a field has been set.
func (o *LinterResourceSpec) HasName() bool {
	if o != nil && !isNil(o.Name) {
		return true
	}

	return false
}

// SetName gets a reference to the given string and assigns it to the Name field.
func (o *LinterResourceSpec) SetName(v string) {
	o.Name = &v
}

// GetEnabled returns the Enabled field value if set, zero value otherwise.
func (o *LinterResourceSpec) GetEnabled() bool {
	if o == nil || isNil(o.Enabled) {
		var ret bool
		return ret
	}
	return *o.Enabled
}

// GetEnabledOk returns a tuple with the Enabled field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *LinterResourceSpec) GetEnabledOk() (*bool, bool) {
	if o == nil || isNil(o.Enabled) {
		return nil, false
	}
	return o.Enabled, true
}

// HasEnabled returns a boolean if a field has been set.
func (o *LinterResourceSpec) HasEnabled() bool {
	if o != nil && !isNil(o.Enabled) {
		return true
	}

	return false
}

// SetEnabled gets a reference to the given bool and assigns it to the Enabled field.
func (o *LinterResourceSpec) SetEnabled(v bool) {
	o.Enabled = &v
}

// GetMinimumScore returns the MinimumScore field value if set, zero value otherwise.
func (o *LinterResourceSpec) GetMinimumScore() int32 {
	if o == nil || isNil(o.MinimumScore) {
		var ret int32
		return ret
	}
	return *o.MinimumScore
}

// GetMinimumScoreOk returns a tuple with the MinimumScore field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *LinterResourceSpec) GetMinimumScoreOk() (*int32, bool) {
	if o == nil || isNil(o.MinimumScore) {
		return nil, false
	}
	return o.MinimumScore, true
}

// HasMinimumScore returns a boolean if a field has been set.
func (o *LinterResourceSpec) HasMinimumScore() bool {
	if o != nil && !isNil(o.MinimumScore) {
		return true
	}

	return false
}

// SetMinimumScore gets a reference to the given int32 and assigns it to the MinimumScore field.
func (o *LinterResourceSpec) SetMinimumScore(v int32) {
	o.MinimumScore = &v
}

// GetPlugins returns the Plugins field value if set, zero value otherwise.
func (o *LinterResourceSpec) GetPlugins() []LinterResourcePlugin {
	if o == nil || isNil(o.Plugins) {
		var ret []LinterResourcePlugin
		return ret
	}
	return o.Plugins
}

// GetPluginsOk returns a tuple with the Plugins field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *LinterResourceSpec) GetPluginsOk() ([]LinterResourcePlugin, bool) {
	if o == nil || isNil(o.Plugins) {
		return nil, false
	}
	return o.Plugins, true
}

// HasPlugins returns a boolean if a field has been set.
func (o *LinterResourceSpec) HasPlugins() bool {
	if o != nil && !isNil(o.Plugins) {
		return true
	}

	return false
}

// SetPlugins gets a reference to the given []LinterResourcePlugin and assigns it to the Plugins field.
func (o *LinterResourceSpec) SetPlugins(v []LinterResourcePlugin) {
	o.Plugins = v
}

func (o LinterResourceSpec) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o LinterResourceSpec) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !isNil(o.Id) {
		toSerialize["id"] = o.Id
	}
	if !isNil(o.Name) {
		toSerialize["name"] = o.Name
	}
	if !isNil(o.Enabled) {
		toSerialize["enabled"] = o.Enabled
	}
	if !isNil(o.MinimumScore) {
		toSerialize["minimumScore"] = o.MinimumScore
	}
	if !isNil(o.Plugins) {
		toSerialize["plugins"] = o.Plugins
	}
	return toSerialize, nil
}

type NullableLinterResourceSpec struct {
	value *LinterResourceSpec
	isSet bool
}

func (v NullableLinterResourceSpec) Get() *LinterResourceSpec {
	return v.value
}

func (v *NullableLinterResourceSpec) Set(val *LinterResourceSpec) {
	v.value = val
	v.isSet = true
}

func (v NullableLinterResourceSpec) IsSet() bool {
	return v.isSet
}

func (v *NullableLinterResourceSpec) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableLinterResourceSpec(val *LinterResourceSpec) *NullableLinterResourceSpec {
	return &NullableLinterResourceSpec{value: val, isSet: true}
}

func (v NullableLinterResourceSpec) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableLinterResourceSpec) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
