source "https://rubygems.org"

gem "puma",     "~> 6.4.2"
gem "sinatra",  "~> 3.0.5"

# Adding support for Open Telemetry
gem 'opentelemetry-sdk'
gem 'opentelemetry-exporter-otlp'
gem 'opentelemetry-instrumentation-all'
